import type { VideoItem } from '../types';

export const sampleVideos: VideoItem[] = [
  {
    id: '1',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    title: 'Big Buck Bunny',
    description: 'Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself.',
    duration: 596,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
    tags: ['animation', 'comedy', 'short'],
    createdAt: '2024-01-15T10:00:00Z',
    views: 125000,
    progress: 0.35,
  },
  {
    id: '2',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    title: 'Elephants Dream',
    description: 'The first Blender Open Movie from 2006.',
    duration: 653,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg',
    tags: ['animation', 'sci-fi'],
    createdAt: '2024-01-20T10:00:00Z',
    views: 85000,
  },
  {
    id: '3',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'For Bigger Blazes',
    description: 'HBO GO now icons notes an icon of a screen that says "Go Photo Gallery" with arrows pointing.',
    duration: 15,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg',
    tags: ['promo', 'hbo'],
    createdAt: '2024-01-10T10:00:00Z',
    views: 45000,
    progress: 1,
  },
  {
    id: '4',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'For Bigger Escapes',
    description: 'Introducing Chromecast. The easiest way to enjoy online video on your TV.',
    duration: 15,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
    tags: ['promo', 'chromecast'],
    createdAt: '2024-02-01T10:00:00Z',
    views: 220000,
  },
  {
    id: '5',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'For Bigger Fun',
    description: 'Introducing Chromecast. The easiest way to enjoy online video on your TV.',
    duration: 60,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg',
    tags: ['promo', 'chromecast'],
    createdAt: '2024-02-05T10:00:00Z',
    views: 180000,
    progress: 0.5,
  },
  {
    id: '6',
    src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'For Bigger Joyrides',
    description: 'Introducing Chromecast. The easiest way to enjoy online video on your TV.',
    duration: 15,
    thumbnail: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg',
    tags: ['promo', 'chromecast'],
    createdAt: '2024-02-10T10:00:00Z',
    views: 95000,
  },
];

export const singleVideo = sampleVideos[0]!;
